NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.75
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.6
NDefines.NGraphics.COUNTRY_GRADIENT_POWER = 1.5
NDefines.NGraphics.COUNTRY_EDGE_SOFTNESS = 0.2