NDefines.NGraphics.SUN_HEIGHT = 1200
NDefines.NGraphics.SUN_INTENSITY = 0.9
NDefines.NGraphics.COUNTRY_EDGE_SOFTNESS = 0.25
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.6
NDefines_Graphics.NGraphics.BLOOM_SCALE = 0.0
NDefines.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.9
NDefines.NGraphics.GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_COUNTRY = 0.018